apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
  labels:
    app: sso
data: # all values Base64
  POSTGRES_DATABASE:  <Database Name>
  POSTGRES_EXTERNAL_ADDRESS: <External Database  IP or URL (resolvable by K8s)>
  POSTGRES_EXTERNAL_PORT: <External  Database Port>
  POSTGRES_PASSWORD: <Database Password>
  POSTGRES_USERNAME:  <Database Username>
type: Opaque