apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: dev
build:
  artifacts:
  - image: CODE_IMAGE
    context: build/code-server
  - image: INITIALIZERS_IMAGE
    context: build/initializers
  - image: JUPYTER_IMAGE
    context: build/jupyter
  - image: PGWEB_IMAGE
    context: build/pgweb
  googleCloudBuild:
    timeout: 3600s
deploy:
  helm:
    releases:
    - name: workstation-prereqs
      chartPath: prepare/chart
      namespace: kube-system
    - name: workstation
      chartPath: deploy
      namespace: default
      setValues:
        policies.enabled: false
      artifactOverrides:
        code.image: CODE_IMAGE
        initializers.image: INITIALIZERS_IMAGE
        jupyter.image: JUPYTER_IMAGE
        pgweb.image: PGWEB_IMAGE
      imageStrategy:
        helm: {}