{{ if eq .Values.pgweb.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: pgweb
  labels:
    app: pgweb
spec:
  type: ClusterIP
  ports:
  - name: pgweb
    port: 80
    targetPort: 8081
  selector:
    app: pgweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
  labels:
    app: pgweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      {{ toYaml .Values.podDefaults | nindent 6 }}
      {{ include "affinity" .Values.pgweb | indent 6 }}
      {{ include "tolerations" .Values.pgweb | indent 6 }}
      containers:
      - name: pgweb
        image: {{ .Values.pgweb.image }}
        resources: {{ toYaml .Values.pgweb.resources | nindent 10 }}
{{ if eq .Values.policies.enabled true }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pgweb
spec:
  podSelector:
    matchLabels:
      app: pgweb
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ingress-nginx
    - namespaceSelector: {}
  egress:
  - {}
{{ end }}
{{ end }}