{{ if eq .Values.selenium.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    name: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
  - name: web
    port: 80
    targetPort: 4444
  - name: tests
    port: 4444
    targetPort: 4444
  - name: event-bus-publish
    port: 4442
    targetPort: 4442
  - name: event-bus-subscribe
    port: 4443
    targetPort: 4443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
    name: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      {{ toYaml .Values.podDefaults | nindent 6 }}
      {{ include "affinity" .Values.selenium.hub | indent 6 }}
      {{ include "tolerations" .Values.selenium.hub | indent 6 }}
      containers:
      - name: selenium-hub
        image: {{ .Values.selenium.hub.image }}
        resources: {{ toYaml .Values.selenium.hub.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
{{ if eq .Values.policies.enabled true }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: selenium-hub
spec:
  podSelector:
    matchLabels:
      app: selenium-hub
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - {}
  egress:
  - to:
{{ if eq .Values.selenium.chrome.enabled true }}
    - podSelector:
        matchLabels:
          app: selenium-chrome
{{ end }}
{{ if eq .Values.selenium.firefox.enabled true }}
    - podSelector:
        matchLabels:
          app: selenium-firefox
{{ end }}
{{ if eq .Values.selenium.edge.enabled true }}
    - podSelector:
        matchLabels:
          app: selenium-edge
{{ end }}
{{ end }}
{{ if eq .Values.selenium.chrome.enabled true }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chrome
  labels:
    app: selenium-chrome
    name: selenium-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-chrome
  template:
    metadata:
      labels:
        app: selenium-chrome
    spec:
      {{ toYaml .Values.podDefaults | nindent 6 }}
      {{ include "affinity" .Values.selenium.chrome | indent 6 }}
      {{ include "tolerations" .Values.selenium.chrome | indent 6 }}
      containers:
      - name: selenium-chrome
        image: {{ .Values.selenium.chrome.image }}
        env:
        - name: SE_EVENT_BUS_HOST
          value: "selenium-hub"
        - name: SE_EVENT_BUS_PUBLISH_PORT
          value: "4442"
        - name: SE_EVENT_BUS_SUBSCRIBE_PORT
          value: "4443"
        - name: VNC_NO_PASSWORD
          value: "1"
        resources: {{ toYaml .Values.selenium.chrome.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome
spec:
  type: ClusterIP
  ports:
  - name: novnc
    port: 80
    targetPort: 7900
  selector:
    app: selenium-chrome
{{ if eq .Values.policies.enabled true }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: selenium-chrome
spec:
  podSelector:
    matchLabels:
      app: selenium-chrome
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ingress-nginx
    - podSelector:
        matchLabels:
          app: selenium-hub
    - namespaceSelector: {}
  egress:
  - {}
{{ end }}
{{ end }}
{{ if eq .Values.selenium.firefox.enabled true }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-firefox
  labels:
    app: selenium-firefox
    name: selenium-firefox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-firefox
  template:
    metadata:
      labels:
        app: selenium-firefox
    spec:
      {{ toYaml .Values.podDefaults | nindent 6 }}
      {{ include "affinity" .Values.selenium.firefox | indent 6 }}
      {{ include "tolerations" .Values.selenium.firefox | indent 6 }}
      containers:
      - name: selenium-firefox
        image: {{ .Values.selenium.firefox.image }}
        env:
        - name: SE_EVENT_BUS_HOST
          value: "selenium-hub"
        - name: SE_EVENT_BUS_PUBLISH_PORT
          value: "4442"
        - name: SE_EVENT_BUS_SUBSCRIBE_PORT
          value: "4443"
        - name: VNC_NO_PASSWORD
          value: "1"
        resources: {{ toYaml .Values.selenium.firefox.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-firefox
spec:
  type: ClusterIP
  ports:
  - name: novnc
    port: 80
    targetPort: 7900
  selector:
    app: selenium-firefox
{{ if eq .Values.policies.enabled true }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: selenium-firefox
spec:
  podSelector:
    matchLabels:
      app: selenium-firefox
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ingress-nginx
    - podSelector:
        matchLabels:
          app: selenium-hub
    - namespaceSelector: {}
  egress:
  - {}
{{ end }}
{{ end }}
{{ if eq .Values.selenium.edge.enabled true }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-edge
  labels:
    app: selenium-edge
    name: selenium-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-edge
  template:
    metadata:
      labels:
        app: selenium-edge
    spec:
      {{ toYaml .Values.podDefaults | nindent 6 }}
      {{ include "affinity" .Values.selenium.edge | indent 6 }}
      {{ include "tolerations" .Values.selenium.edge | indent 6 }}
      containers:
      - name: selenium-edge
        image: {{ .Values.selenium.edge.image }}
        env:
        - name: SE_EVENT_BUS_HOST
          value: "selenium-hub"
        - name: SE_EVENT_BUS_PUBLISH_PORT
          value: "4442"
        - name: SE_EVENT_BUS_SUBSCRIBE_PORT
          value: "4443"
        - name: VNC_NO_PASSWORD
          value: "1"
        resources: {{ toYaml .Values.selenium.edge.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-edge
spec:
  type: ClusterIP
  ports:
  - name: novnc
    port: 80
    targetPort: 7900
  selector:
    app: selenium-edge
{{ if eq .Values.policies.enabled true }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: selenium-edge
spec:
  podSelector:
    matchLabels:
      app: selenium-edge
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ingress-nginx
    - podSelector:
        matchLabels:
          app: selenium-hub
    - namespaceSelector: {}
  egress:
  - {}
{{ end }}
{{ end }}
{{ end }}