name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: setup up qemu
      uses: docker/setup-qemu-action@v1

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v1

    - name: build code server image
      uses: docker/build-push-action@v2
      with:
        context: ./build/code-server/
        push: false
        tags: khulnasoft-lab/cloudformat-code-server:latest

    - name: build keycloak seeding image
      uses: docker/build-push-action@v2
      with:
        context: ./build/initializers/
        push: false
        tags: khulnasoft-lab/cloudformat-initializers:latest

    - name: build jupyter image
      uses: docker/build-push-action@v2
      with:
        context: ./build/jupyter/
        push: false
        tags: khulnasoft-lab/cloudformat-jupyter:latest

    - name: build pgweb image
      uses: docker/build-push-action@v2
      with:
        context: ./build/pgweb/
        push: false
        tags: khulnasoft-lab/cloudformat-pgweb:latest
